from __future__ import annotations

import asyncio
import discord
from discord.ext import commands, tasks
from discord import app_commands
from datetime import datetime, time
import config
import providers
import db as database


DIGEST_PROMPT = """You are summarizing a Discord server's daily conversation activity.
Review the messages below and create a concise daily digest that includes:
1. **Key Topics Discussed** — main subjects that came up
2. **Important Decisions or Announcements** — anything notable
3. **Active Participants** — who contributed most
4. **Questions Left Unanswered** — anything still unresolved
5. **Highlights** — interesting or fun moments

Keep it friendly, concise, and easy to scan. Use Discord markdown formatting."""


def _parse_time(time_str: str) -> time:
    """Parse a time string like '09:00' into a time object."""
    try:
        hour, minute = map(int, time_str.strip().split(":"))
        return time(hour=hour, minute=minute)
    except Exception:
        return time(hour=9, minute=0)


class Digest(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.digest_task.start()

    def cog_unload(self):
        self.digest_task.cancel()

    @tasks.loop(minutes=1)
    async def digest_task(self):
        """Check every minute if it's time to send the daily digest."""
        now = datetime.now()

        for guild in self.bot.guilds:
            guild_id = str(guild.id)

            enabled = await database.get_digest_config(guild_id, "DIGEST_ENABLED")
            if not enabled or enabled.lower() != "true":
                continue

            digest_time_str = await database.get_digest_config(guild_id, "DIGEST_TIME") or "09:00"
            digest_time = _parse_time(digest_time_str)

            # Check if current time matches digest time (within the same minute)
            if now.hour == digest_time.hour and now.minute == digest_time.minute:
                # Avoid sending twice in the same minute
                last_sent = await database.get_digest_config(guild_id, "DIGEST_LAST_SENT")
                today_str = now.strftime("%Y-%m-%d %H:%M")
                if last_sent == today_str:
                    continue

                await database.set_digest_config(guild_id, "DIGEST_LAST_SENT", today_str)
                await self._send_digest(guild)

    @digest_task.before_loop
    async def before_digest_task(self):
        await self.bot.wait_until_ready()

    async def _send_digest(self, guild: discord.Guild):
        """Generate and send the daily digest for a guild."""
        guild_id = str(guild.id)
        channel_id = await database.get_digest_config(guild_id, "DIGEST_CHANNEL_ID")

        if not channel_id:
            return

        channel = guild.get_channel(int(channel_id))
        if not channel:
            return

        try:
            # Collect messages from past 24 hours from DB
            messages = await database.get_recent_messages_for_digest(guild_id, hours=24)

            if not messages:
                await channel.send("📋 **Daily Digest** — No conversation activity in the past 24 hours.")
                return

            # Format messages for AI
            formatted = "\n".join(
                f"[{m['created_at']}] {m['role']}: {m['content'][:200]}"
                for m in messages[:100]  # Cap at 100 messages
            )

            history = [{"role": "user", "content": f"Here are today's messages:\n\n{formatted}"}]

            loop = asyncio.get_event_loop()
            response, provider_name = await loop.run_in_executor(
                None, providers.chat, history, DIGEST_PROMPT
            )

            provider_label = config.PROVIDERS.get(provider_name, {}).get("name", provider_name)
            now = datetime.now()

            embed = discord.Embed(
                title=f"📋 Daily Digest — {now.strftime('%B %d, %Y')}",
                description=response[:4000],
                color=discord.Color.gold(),
                timestamp=now
            )
            embed.set_footer(text=f"Generated by {provider_label} • SparkSage")
            await channel.send(embed=embed)

        except Exception as e:
            print(f"Error sending digest for guild {guild_id}: {e}")

    # --- Admin Commands ---

    digest_group = app_commands.Group(
        name="digest",
        description="Configure the daily digest (Admin only)"
    )

    @digest_group.command(name="enable", description="Enable the daily digest")
    @app_commands.checks.has_permissions(manage_guild=True)
    async def digest_enable(self, interaction: discord.Interaction):
        await database.set_digest_config(str(interaction.guild_id), "DIGEST_ENABLED", "true")
        await interaction.response.send_message("✅ Daily digest enabled!")

    @digest_group.command(name="disable", description="Disable the daily digest")
    @app_commands.checks.has_permissions(manage_guild=True)
    async def digest_disable(self, interaction: discord.Interaction):
        await database.set_digest_config(str(interaction.guild_id), "DIGEST_ENABLED", "false")
        await interaction.response.send_message("⏸️ Daily digest disabled.")

    @digest_group.command(name="setchannel", description="Set the channel for daily digests")
    @app_commands.describe(channel="Channel to post the daily digest in")
    @app_commands.checks.has_permissions(manage_guild=True)
    async def digest_setchannel(self, interaction: discord.Interaction, channel: discord.TextChannel):
        await database.set_digest_config(str(interaction.guild_id), "DIGEST_CHANNEL_ID", str(channel.id))
        await interaction.response.send_message(f"✅ Digest channel set to {channel.mention}")

    @digest_group.command(name="settime", description="Set the time to send the daily digest (24h format)")
    @app_commands.describe(digest_time="Time in HH:MM format, e.g. 09:00 or 18:30")
    @app_commands.checks.has_permissions(manage_guild=True)
    async def digest_settime(self, interaction: discord.Interaction, digest_time: str):
        try:
            parsed = _parse_time(digest_time)
            await database.set_digest_config(
                str(interaction.guild_id), "DIGEST_TIME",
                f"{parsed.hour:02d}:{parsed.minute:02d}"
            )
            await interaction.response.send_message(
                f"✅ Daily digest will be sent at **{parsed.hour:02d}:{parsed.minute:02d}** every day."
            )
        except Exception:
            await interaction.response.send_message(
                "❌ Invalid time format. Use HH:MM, e.g. `09:00` or `18:30`", ephemeral=True
            )

    @digest_group.command(name="status", description="View current digest configuration")
    @app_commands.checks.has_permissions(manage_guild=True)
    async def digest_status(self, interaction: discord.Interaction):
        guild_id = str(interaction.guild_id)
        enabled = await database.get_digest_config(guild_id, "DIGEST_ENABLED") or "false"
        channel_id = await database.get_digest_config(guild_id, "DIGEST_CHANNEL_ID")
        digest_time = await database.get_digest_config(guild_id, "DIGEST_TIME") or "09:00"
        last_sent = await database.get_digest_config(guild_id, "DIGEST_LAST_SENT") or "Never"

        channel_display = f"<#{channel_id}>" if channel_id else "*(not set)*"

        embed = discord.Embed(
            title="⚙️ Daily Digest Configuration",
            color=discord.Color.gold()
        )
        embed.add_field(name="Status", value="✅ Enabled" if enabled == "true" else "⏸️ Disabled", inline=True)
        embed.add_field(name="Channel", value=channel_display, inline=True)
        embed.add_field(name="Time", value=f"**{digest_time}** daily", inline=True)
        embed.add_field(name="Last Sent", value=last_sent, inline=True)
        await interaction.response.send_message(embed=embed)

    @digest_group.command(name="test", description="Send a test digest right now")
    @app_commands.checks.has_permissions(manage_guild=True)
    async def digest_test(self, interaction: discord.Interaction):
        await interaction.response.defer()
        try:
            await self._send_digest(interaction.guild)
            await interaction.followup.send("✅ Test digest sent!")
        except Exception as e:
            await interaction.followup.send(f"❌ Failed to send digest: {e}")

    # --- Error Handler ---

    @digest_enable.error
    @digest_disable.error
    @digest_setchannel.error
    @digest_settime.error
    @digest_status.error
    @digest_test.error
    async def digest_error(self, interaction: discord.Interaction, error: app_commands.AppCommandError):
        if isinstance(error, app_commands.MissingPermissions):
            await interaction.response.send_message(
                "❌ You need **Manage Server** permission to use this command.", ephemeral=True
            )


async def setup(bot: commands.Bot):
    await bot.add_cog(Digest(bot))